name: Deploy to Hostinger

on:
  push:
    branches: [main,amazon]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /domains/jqd.io/public_html/work/amazon/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/src/**
            **/package.json
            **/package-lock.json
            **/README.md
